# Generated by Django 3.2.7 on 2021-09-20 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of service', max_length=50)),
                ('provider_name', models.CharField(help_text='Provider name', max_length=50)),
                ('price', models.IntegerField(help_text='Price')),
                ('Servicer_contact', models.CharField(help_text='Contact of service provider', max_length=12)),
                ('serviceadd_date', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Querydata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(help_text='Type of query', max_length=50)),
                ('query_detail', models.TextField(help_text='Detail of query')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queriess', to='app.service')),
            ],
        ),
    ]
