# Generated by Django 3.2.6 on 2021-09-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210924_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querydata1_loc',
            name='creator',
        ),
    ]
