# Generated by Django 3.2.6 on 2021-09-25 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_querydata1_loc_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Querydata1_loc',
            new_name='Query',
        ),
    ]
