# Generated by Django 3.2.6 on 2021-09-25 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20210925_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='creator',
        ),
        migrations.AddField(
            model_name='query',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
