# Generated by Django 3.2.6 on 2021-09-26 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_remove_service_loc_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='creator',
        ),
        migrations.AddField(
            model_name='query',
            name='creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
