# Generated by Django 3.2.6 on 2021-09-26 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuery',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('query_type', models.CharField(help_text='Type of query', max_length=50)),
                ('query_detail', models.TextField(help_text='Detail of query')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.postquery')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
