# Generated by Django 3.2.6 on 2021-09-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_postquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquery',
            name='parent',
        ),
    ]
