# Generated by Django 3.2.6 on 2021-09-27 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_postquery_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquery',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.postquery'),
        ),
    ]
