# Generated by Django 3.2.6 on 2021-09-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_postquery_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postquery',
            old_name='qno',
            new_name='sno',
        ),
    ]
