# Generated by Django 3.2.6 on 2021-09-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_qno_postquery_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='provider',
        ),
    ]
