# Generated by Django 3.2.6 on 2021-09-28 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210928_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='provider_contact',
            field=models.CharField(blank=True, default='+91-', help_text='Contact of service provider', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91-9999999999'. Up to 10 digits allowed.", regex='[+](0|91)?[-][7-9]\\d{8}')]),
        ),
    ]
